# Generated by Django 6.0.4 on 2026-04-18 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Original input text (max 2000 chars)', max_length=2000)),
                ('text_preview', models.CharField(blank=True, max_length=200)),
                ('thematic_labels', models.JSONField(default=list, help_text="e.g. ['Anxiety', 'Depression']")),
                ('categorical_labels', models.JSONField(default=list, help_text="e.g. ['Panic', 'Hopelessness']")),
                ('trigger_labels', models.JSONField(default=list, help_text="e.g. ['Work', 'Financial']")),
                ('thematic_scores', models.JSONField(default=dict)),
                ('categorical_scores', models.JSONField(default=dict)),
                ('trigger_scores', models.JSONField(default=dict)),
                ('severity', models.IntegerField(default=1, help_text='1 (minimal) to 5 (critical)')),
                ('severity_probabilities', models.JSONField(default=list)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('model_used', models.CharField(choices=[('svm', 'Support Vector Machine'), ('rf', 'Random Forest'), ('lstm', 'Bidirectional LSTM')], default='lstm', max_length=10)),
                ('processing_time_ms', models.FloatField(default=0.0)),
                ('alert_triggered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Analysis Record',
                'verbose_name_plural': 'Analysis Records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='analysis_an_created_54fd1b_idx'), models.Index(fields=['severity'], name='analysis_an_severit_e7fe6c_idx'), models.Index(fields=['alert_triggered'], name='analysis_an_alert_t_b5d09e_idx'), models.Index(fields=['model_used'], name='analysis_an_model_u_e0a443_idx')],
            },
        ),
        migrations.CreateModel(
            name='AlertLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('severity_status', models.CharField(max_length=20)),
                ('alert_message', models.TextField()),
                ('recommendation', models.TextField()),
                ('empathetic_response', models.TextField(blank=True, null=True)),
                ('resources', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert_log', to='analysis.analysisrecord')),
            ],
            options={
                'verbose_name': 'Alert Log',
                'verbose_name_plural': 'Alert Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
